export { evaluateCondition } from './conditions/evaluate.js';
export type { ConditionEvaluation } from './conditions/evaluate.js';
export { resolveFieldValue } from './conditions/field-reference.js';
export type { ConditionScope, ResolvedFieldValue } from './conditions/field-reference.js';
export { applyOperator, UnknownConditionOperatorError } from './conditions/operators.js';
export type { OperatorOutcome } from './conditions/operators.js';
export { advance } from './engine/advance.js';
export { resolveAssignment, resolveAssignmentWithValues } from './engine/assignment.js';
export type { ResolvedAssignment } from './engine/assignment.js';
export { computeDueAt } from './engine/sla.js';
export { addCalendarHours, addWorkingHours, DEFAULT_CALENDAR } from './engine/calendar.js';
export { cloneTemplate, uniqueKey } from './templates/clone.js';
export type { CloneTemplateInput, CloneTemplateResult, CloneWarning } from './templates/clone.js';
